// Copyright 2025 KONGSBERG
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions are met:
//
// 1. Redistributions of source code must retain the above copyright notice,
//    this list of conditions and the following disclaimer.
//
// 2. Redistributions in binary form must reproduce the above copyright notice,
//    this list of conditions and the following disclaimer in the documentation
//    and/or other materials provided with the distribution.
//
// 3. Neither the name of the copyright holder nor the names of its contributors
//    may be used to endorse or promote products derived from this software
//    without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
// ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
// WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
// DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
// FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
// DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
// SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
// CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
// OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
// OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

// Test complex type scenarios and edge cases

// Recursive types through forward declarations
struct TreeNode;
struct TreeNode {
    long value;
    sequence<TreeNode> children;
    @shared TreeNode parent;  // Optional in IDL, can be null
};

// Mutually recursive types
struct Expression;
struct Statement;

enum ExprType {
    LITERAL,
    BINARY,
    CALL,
    STMT_EXPR
};

struct BinaryExpr {
    @shared Expression left;
    @shared Expression right;
    string op;
};

struct CallExpr {
    string name;
    sequence<Expression> args;
};

union ExprData switch (ExprType) {
    case LITERAL:
        long literal_value;
    case BINARY:
        BinaryExpr binary;
    case CALL:
        CallExpr call;
    case STMT_EXPR:
        @shared Statement stmt;
};

struct Expression {
    ExprData data;
};

enum StmtType {
    EXPR_STMT,
    BLOCK,
    IF_STMT
};

struct IfStmt {
    @shared Expression condition;
    @shared Statement then_stmt;
    @shared Statement else_stmt;
};

union StmtData switch (StmtType) {
    case EXPR_STMT:
        @shared Expression expr;
    case BLOCK:
        sequence<Statement> statements;
    case IF_STMT:
        IfStmt if_stmt;
};

struct Statement {
    StmtData data;
};

// Complex nested types
module collections {
    struct StringLongPair {
        string first;
        long second;
    };
    
    struct LongDoublePair {
        long first;
        double second;
    };
    
    typedef sequence<StringLongPair> StringIntPairs;
    typedef map<string, sequence<LongDoublePair>> ComplexMap;
    
    // Multi-dimensional arrays with typedef chains
    typedef long Row[10];
    typedef Row Matrix[10];
    typedef Matrix Tensor[10];
    
    // Nested sequences and maps
    typedef sequence<sequence<sequence<long>>> Tensor3D;
    typedef map<string, map<string, map<string, long>>> NestedMap;
};

// Union with complex discriminator
module protocol {
    enum MessageType {
        REQUEST = 0x0100,
        RESPONSE = 0x0200,
        NOTIFICATION = 0x0300,
        ERROR = 0x0400
    };
    
    struct Header {
        MessageType type;
        long sequence_num;
        string sender_id;
    };
    
    struct RequestMsg {
        string method;
        any params;  // Using 'any' type
    };
    
    struct ResponseMsg {
        long request_seq;
        any result;
        boolean success;
    };
    
    struct NotificationMsg {
        string event;
        any data;
    };
    
    struct ErrorMsg {
        long error_code;
        string message;
        any details;
    };
    
    union MessageBody switch (MessageType) {
        case REQUEST:
            RequestMsg request;
            
        case RESPONSE:
            ResponseMsg response;
            
        case NOTIFICATION:
            NotificationMsg notification;
            
        case ERROR:
            ErrorMsg error;
    };
    
    struct Message {
        MessageBody body;
    };
};

// Interface inheritance with complex types
interface Base {
    any getValue(in string key);
    void setValue(in string key, in any value);
};

interface Extended : Base {
    typedef map<string, any> ValueMap;
    
    ValueMap getAllValues();
    void setAllValues(in ValueMap values);
    
    // Different method name to avoid overloading
    any getValueWithDefault(in string key, in any default_value);
};

// Valuetype with complex members - TODO: implement valuetype support
// valuetype ComplexValue {
//     public sequence<long> int_list;
//     public map<string, double> double_map;
//     private TreeNode internal_tree;
//     
//     factory create(in sequence<long> ints, in map<string, double> doubles);
// };

// Constants with complex expressions
const long EXPR1 = 10 + 20 * 30;
const long EXPR2 = (100 + 200) / 3;
const long EXPR3 = 0xFF & 0x0F;
const long EXPR4 = 1 << 8 | 1 << 4 | 1;

// Enum references in expressions
const long MSG_MASK = protocol::MessageType::REQUEST | 
                      protocol::MessageType::RESPONSE;
const long ERROR_BASE = protocol::MessageType::ERROR + 1000;