// Copyright 2025 KONGSBERG
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions are met:
//
// 1. Redistributions of source code must retain the above copyright notice,
//    this list of conditions and the following disclaimer.
//
// 2. Redistributions in binary form must reproduce the above copyright notice,
//    this list of conditions and the following disclaimer in the documentation
//    and/or other materials provided with the distribution.
//
// 3. Neither the name of the copyright holder nor the names of its contributors
//    may be used to endorse or promote products derived from this software
//    without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
// ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
// WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
// DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
// FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
// DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
// SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
// CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
// OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
// OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

use std::collections::HashMap;
use std::fmt::Write;
use std::path::PathBuf;

use ic_emit::File;
use ic_emit::printer::{Twine, w};
use ic_hir::ResolvedGraph;
use ic_hir::annotation::{Optional, find_annotation};
use ic_hir::hir::{
    Ann, Decl, Def, DefId, DefKind, InterfaceTy, Member, ModuleTy, Numeric, ParamKind, PrimitiveTy,
    ProtoTy, Ty, TyKind,
};
use ic_vfs::{FileId, SourceMap};

use crate::CppOptions;
use crate::deps::collect_def_dependencies;

type Path = Vec<String>;

pub struct CppGen<'a> {
    pub(crate) hir: &'a ResolvedGraph,
    pub(crate) options: CppOptions,
    source_map: &'a SourceMap,
}

impl<'a> CppGen<'a> {
    pub fn new(hir: &'a ResolvedGraph, source_map: &'a SourceMap, options: CppOptions) -> Self {
        Self {
            hir,
            options,
            source_map,
        }
    }

    fn emit_generated_header(&self, w: &mut Twine) {
        const PKG_VERSION: &str = env!("CARGO_PKG_VERSION");
        w!(w, "// @generated by ic-idl ", PKG_VERSION, "\n\n");
    }

    /// Returns the export macro prefix (including a trailing space) to place on
    /// declarations of functions that are defined in the `.cpp` file, or an
    /// empty string when `--dll-export` was not given.
    fn export_prefix(&self) -> String {
        match &self.options.dll_export {
            Some(sym) => format!("{sym} "),
            None => String::new(),
        }
    }

    fn cpp_name(&self, def_id: DefId) -> &str {
        &self.hir.context.definitions.get(def_id).ident.name
    }

    fn get_scope(&self, def_id: DefId) -> Option<DefId> {
        let def = self.hir.context.definitions.get(def_id);
        let mut current = def.parent?;

        loop {
            let def = self.hir.context.definitions.get(current);
            if matches!(
                def.kind,
                DefKind::Module(_) | DefKind::Interface(_) | DefKind::Valuetype(_)
            ) {
                return Some(current);
            }
            if self.options.scoped_enums && matches!(def.kind, DefKind::Enum(_)) {
                return Some(current);
            }
            current = def.parent?;
        }
    }

    fn common_scope(&self, def_id1: DefId, def_id2: DefId) -> Option<DefId> {
        let mut scope1 = self.get_scope(def_id1)?;
        let mut scope2 = self.get_scope(def_id2)?;

        let mut ancestors1 = Vec::new();
        loop {
            ancestors1.push(scope1);
            scope1 = match self.get_scope(scope1) {
                Some(s) => s,
                None => break,
            };
        }

        loop {
            if ancestors1.contains(&scope2) {
                return Some(scope2);
            }
            scope2 = self.get_scope(scope2)?;
        }
    }

    fn build_path_from(&self, from_scope: DefId, to_scope: Option<DefId>) -> Path {
        let mut path = Vec::new();
        let mut current = from_scope;

        loop {
            if Some(current) == to_scope {
                break;
            }

            let def = self.hir.context.definitions.get(current);
            path.push(def.ident.name.clone());

            current = match self.get_scope(current) {
                Some(scope) => scope,
                None => break,
            };
        }

        path.reverse();
        path
    }

    pub fn scoped_name(
        &self,
        target_def_id: DefId,
        relative_to_def_id: impl Into<Option<DefId>>,
    ) -> String {
        let type_name = self.cpp_name(target_def_id).to_string();
        let relative_to_def_id = relative_to_def_id.into();
        let target_scope_id = self
            .hir
            .context
            .scopes
            .find_scope_containing_def(target_def_id);

        let Some(target_scope_id) = target_scope_id else {
            return type_name;
        };

        if let Some(relative_to_def_id) = relative_to_def_id {
            let current_scope_id = self
                .hir
                .context
                .scopes
                .find_scope_containing_def(relative_to_def_id);

            if Some(target_scope_id) == current_scope_id {
                return type_name;
            }

            if current_scope_id.is_some() {
                let Some(target_scope) = self.get_scope(target_def_id) else {
                    // Target is at global scope, we're in a nested scope
                    return format!("::{type_name}");
                };
                let common = self.common_scope(target_def_id, relative_to_def_id);
                if common == Some(target_scope) || common == self.get_scope(relative_to_def_id) {
                    let relative_path = self.build_path_from(target_scope, common);
                    let pkg_name = relative_path.join("::");
                    let name = if pkg_name.is_empty() {
                        // Target is in parent scope, need full path with :: prefix
                        if common == Some(target_scope)
                            && common != self.get_scope(relative_to_def_id)
                        {
                            let full_path = self.build_path_from(target_scope, None);
                            let full_pkg_name = full_path.join("::");
                            if full_pkg_name.is_empty() {
                                format!("::{type_name}")
                            } else {
                                format!("::{full_pkg_name}::{type_name}")
                            }
                        } else {
                            type_name
                        }
                    } else {
                        format!("{pkg_name}::{type_name}")
                    };
                    return name;
                }
            }
        }

        let Some(target_scope) = self.get_scope(target_def_id) else {
            // Global scope - need :: prefix if we're inside a relative scope
            if relative_to_def_id.is_some() {
                return format!("::{type_name}");
            }
            return type_name;
        };
        let full_path = self.build_path_from(target_scope, None);
        let pkg_name = full_path.join("::");
        if pkg_name.is_empty() {
            type_name
        } else {
            format!("{pkg_name}::{type_name}")
        }
    }

    pub fn has_default_value(&self, ty: &Ty) -> bool {
        let resolved_ty = match &ty.kind {
            TyKind::Adt(def_id) => self.hir.context.base_type_of(*def_id),
            _ => ty.clone(),
        };

        match &resolved_ty.kind {
            TyKind::Primitive(prim) => matches!(
                prim,
                PrimitiveTy::Int8
                    | PrimitiveTy::Int16
                    | PrimitiveTy::Int32
                    | PrimitiveTy::Int64
                    | PrimitiveTy::UInt8
                    | PrimitiveTy::UInt16
                    | PrimitiveTy::UInt32
                    | PrimitiveTy::UInt64
                    | PrimitiveTy::Bool
                    | PrimitiveTy::Float32
                    | PrimitiveTy::Float64
                    | PrimitiveTy::Float128
                    | PrimitiveTy::Char
                    | PrimitiveTy::WChar
            ),
            TyKind::Array { .. } => true,
            TyKind::Adt(def_id) => {
                let def = self.hir.context.definitions.get(*def_id);
                matches!(def.kind, DefKind::Enum(_) | DefKind::Bitmask(_))
            }
            _ => false,
        }
    }

    pub fn cpp_type(&self, ty: &Ty, relative_def: impl Into<Option<DefId>>) -> String {
        let relative_def_opt = relative_def.into();
        match &ty.kind {
            TyKind::Primitive(prim) => cpp_primitive(*prim).to_string(),
            TyKind::String {
                wide, bound: None, ..
            } => {
                if *wide {
                    "::std::wstring".to_string()
                } else {
                    "::std::string".to_string()
                }
            }
            TyKind::String {
                wide,
                bound: Some(bound),
                ..
            } => {
                if *wide {
                    format!("::ic_cts::bounded_wstring<{bound}>")
                } else {
                    format!("::ic_cts::bounded_string<{bound}>")
                }
            }
            TyKind::Adt(def_id) => self.scoped_name(*def_id, relative_def_opt),
            TyKind::Sequence {
                ty, bound: None, ..
            } => {
                let inner = self.cpp_type(ty, relative_def_opt);
                format!("::std::vector<{inner}>")
            }
            TyKind::Sequence {
                ty,
                bound: Some(bound),
                ..
            } => {
                let inner = self.cpp_type(ty, relative_def_opt);
                format!("::ic_cts::bounded_vector<{inner}, {bound}>")
            }
            TyKind::Map {
                key,
                elem,
                bound: None,
                ..
            } => {
                let key_ty = self.cpp_type(key, relative_def_opt);
                let elem_ty = self.cpp_type(elem, relative_def_opt);
                format!("::std::map<{key_ty}, {elem_ty}>")
            }
            TyKind::Map {
                key,
                elem,
                bound: Some(bound),
                ..
            } => {
                let key_ty = self.cpp_type(key, relative_def_opt);
                let elem_ty = self.cpp_type(elem, relative_def_opt);
                format!("::ic_cts::bounded_map<{key_ty}, {elem_ty}, {bound}>")
            }
            TyKind::Array { ty, len, .. } => {
                let inner = self.cpp_type(ty, relative_def_opt);
                format!("::std::array<{inner}, {len}>")
            }
            TyKind::Any => "::ic_cts::Any".to_string(),
            TyKind::Fixed | TyKind::Null => "void".to_string(),
        }
    }

    pub fn should_use_move(&self, ty: &Ty) -> bool {
        !matches!(&ty.kind, TyKind::Primitive(_))
    }

    pub fn is_optional(member: &Member) -> bool {
        find_annotation::<Optional>(&member.annotations, "optional")
            .and_then(Result::ok)
            .is_some_and(|opt| opt.value)
    }

    pub fn bit_bound(annotations: &[Ann]) -> Option<&Numeric> {
        annotations
            .iter()
            .find(|ann| ann.ident.name == "bit_bound")
            .and_then(|ann| ann.args.first())
            .map(|arg| &arg.value)
    }

    pub fn default_value(annotations: &[Ann]) -> Option<&Numeric> {
        annotations
            .iter()
            .find(|ann| ann.ident.name == "default")
            .and_then(|ann| ann.args.first())
            .map(|arg| &arg.value)
    }

    pub fn emit_member(&self, w: &mut Twine, member: &Member, def_id: DefId) {
        let ty_str = self.cpp_type(&member.ty, def_id);

        if Self::is_optional(member) {
            w!(w, "::std::optional<", ty_str, "> ", member.ident.name, ";\n");
        } else {
            w!(w, ty_str, " ", member.ident.name);
            if let Some(default) = Self::default_value(&member.annotations) {
                let is_array = matches!(default, Numeric::Array { .. });
                if !is_array {
                    w!(w, "{");
                }
                self.emit_numeric_value_with_ty(w, default, &member.ty, def_id);
                if !is_array {
                    w!(w, "}");
                }
            } else if self.has_default_value(&member.ty) {
                w!(w, "{");
                self.emit_default_initializer(w, &member.ty);
                w!(w, "}");
            }
            w!(w, ";\n");
        }
    }

    pub fn collect_all_members(&self, def_id: DefId) -> Vec<Member> {
        let def = self.hir.context.definitions.get(def_id);
        let mut all_members = Vec::new();

        match &def.kind {
            DefKind::Struct(struct_ty) => {
                if let Some(parent) = struct_ty.parent {
                    all_members.extend(self.collect_all_members(parent.def_id));
                }
                all_members.extend(struct_ty.members.clone());
            }
            DefKind::Valuetype(valuetype_ty) => {
                if let Some(parent) = valuetype_ty.parent {
                    all_members.extend(self.collect_all_members(parent.def_id));
                }
                all_members.extend(valuetype_ty.members.clone());
            }
            DefKind::Except(except_ty) => {
                all_members.extend(except_ty.members.clone());
            }
            _ => {}
        }

        all_members
    }

    pub fn emit_numeric_value(
        &self,
        w: &mut Twine,
        value: &Numeric,
        relative_def: impl Into<Option<DefId>>,
    ) {
        self.emit_numeric_value_impl(w, value, relative_def, None, false);
    }

    pub fn emit_numeric_value_with_ty(
        &self,
        w: &mut Twine,
        value: &Numeric,
        ty: &Ty,
        relative_def: impl Into<Option<DefId>>,
    ) {
        self.emit_numeric_value_impl(w, value, relative_def, Some(ty), false);
    }

    fn emit_numeric_value_impl(
        &self,
        w: &mut Twine,
        value: &Numeric,
        relative_def: impl Into<Option<DefId>>,
        expected_ty: Option<&Ty>,
        emit_type_for_struct: bool,
    ) {
        let relative_def_opt = relative_def.into();
        match value {
            Numeric::Null => w!(w, "nullptr"),
            Numeric::Bool(v) => w!(w, if *v { "true" } else { "false" }),
            Numeric::Char(v) => escape_char(w, *v),
            Numeric::WChar(v) => {
                w!(w, "u'");
                _ = write_escaped_char(w, *v);
                w!(w, "'");
            }
            Numeric::Int8(v) => w!(w, v),
            Numeric::UInt8(v) => w!(w, v, "U"),
            Numeric::Int16(v) => w!(w, v),
            Numeric::UInt16(v) => w!(w, v, "U"),
            Numeric::Int32(v) => w!(w, v),
            Numeric::UInt32(v) => w!(w, v, "U"),
            Numeric::Int64(v) => {
                if *v == i64::MIN {
                    w!(w, "INT64_MIN");
                } else {
                    w!(w, v, "LL");
                }
            }
            Numeric::UInt64(v) => w!(w, v, "ULL"),
            Numeric::Float(v) => w!(w, format!("{:.7}", v), "f"),
            Numeric::Double(v) => w!(w, format!("{:.16}", v)),
            Numeric::String(s) => emit_escaped_string(w, s),
            Numeric::WString(s) => {
                w!(w, "u");
                emit_escaped_string(w, s);
            }
            Numeric::Const(const_def_id) => {
                let name = self.scoped_name(*const_def_id, relative_def_opt);
                w!(w, name);
            }
            Numeric::Sequence { values, .. } => {
                w!(w, "{");
                for (i, elem) in values.iter().enumerate() {
                    self.emit_numeric_value(w, elem, relative_def_opt);
                    if i < values.len() - 1 {
                        w!(w, ", ");
                    }
                }
                w!(w, "}");
            }
            Numeric::Array { values, .. } => {
                w!(w, "{{");
                for (i, elem) in values.iter().enumerate() {
                    self.emit_numeric_value(w, elem, relative_def_opt);
                    if i < values.len() - 1 {
                        w!(w, ", ");
                    }
                }
                w!(w, "}}");
            }
            Numeric::Struct {
                fields,
                ty: struct_def_id,
            } => {
                if emit_type_for_struct {
                    let type_name = if let Some(ty) = expected_ty {
                        self.cpp_type(ty, relative_def_opt)
                    } else {
                        self.scoped_name(*struct_def_id, relative_def_opt)
                    };
                    w!(w, type_name, "{");
                }
                for (i, value) in fields.iter().enumerate() {
                    self.emit_numeric_value_impl(w, value, relative_def_opt, None, true);
                    if i < fields.len() - 1 {
                        w!(w, ", ");
                    }
                }
                if emit_type_for_struct {
                    w!(w, "}");
                }
            }
            Numeric::Map { entries, .. } => {
                w!(w, "{");
                for (i, (key, value)) in entries.iter().enumerate() {
                    w!(w, "{ ");
                    self.emit_numeric_value(w, key, relative_def_opt);
                    w!(w, ", ");
                    self.emit_numeric_value(w, value, relative_def_opt);
                    w!(w, " }");
                    if i < entries.len() - 1 {
                        w!(w, ", ");
                    }
                }
                w!(w, "}");
            }
            Numeric::Union { discriminant, .. } => {
                w!(w, "{ ");
                self.emit_numeric_value(w, discriminant, relative_def_opt);
                w!(w, " }");
            }
        }
    }

    pub fn primitive_default(prim: PrimitiveTy) -> &'static str {
        match prim {
            PrimitiveTy::Bool => "false",
            PrimitiveTy::Int8 | PrimitiveTy::Int16 | PrimitiveTy::Int32 | PrimitiveTy::Int64 => "0",
            PrimitiveTy::UInt8 | PrimitiveTy::UInt16 | PrimitiveTy::UInt32 => "0U",
            PrimitiveTy::UInt64 => "0ULL",
            PrimitiveTy::Float32 | PrimitiveTy::Float64 | PrimitiveTy::Float128 => "0.0",
            PrimitiveTy::Char => "'\\0'",
            PrimitiveTy::WChar => "L'\\0'",
            PrimitiveTy::Void => "",
        }
    }

    pub fn emit_default_initializer(&self, w: &mut Twine, ty: &Ty) {
        let resolved = match &ty.kind {
            TyKind::Adt(def_id) => self.hir.context.base_type_of(*def_id),
            _ => ty.clone(),
        };
        match &resolved.kind {
            TyKind::Primitive(prim) => w!(w, Self::primitive_default(*prim)),
            TyKind::Array { .. } => w!(w, "{}"),
            TyKind::Adt(def_id) => {
                let def = self.hir.context.definitions.get(*def_id);
                if let DefKind::Enum(enum_ty) = &def.kind {
                    if let Some(default_member) = enum_ty
                        .fields
                        .iter()
                        .map(|f| self.hir.context.definitions.get(f))
                        .find(|f| {
                            f.annotations
                                .iter()
                                .any(|a| a.ident.name == "default_literal")
                        })
                    {
                        let name = self.scoped_name(default_member.id, None);
                        w!(w, name);
                    } else if let Some(first) = enum_ty.fields.first() {
                        let name = self.scoped_name(*first, None);
                        w!(w, name);
                    }
                }
            }
            _ => {}
        }
    }

    pub fn emit_type_traits(&self, w: &mut Twine, def: &Def) {
        self.emit_type_traits_with_suffix(w, def, "");
    }

    pub fn emit_type_traits_with_suffix(&self, w: &mut Twine, def: &Def, suffix: &str) {
        let qualified_name = self.scoped_name(def.id, None);
        let full_qualified_name = format!("{qualified_name}{suffix}");

        w!(w, "template <>\n");
        w!(w, "struct ic_cts::TypeTraits<", full_qualified_name, "> {\n");
        w!(w, "using value_type = ", full_qualified_name, ";\n");
        w!(w, "using in_type = const ", full_qualified_name, "&;\n");
        w!(w, "using out_type = ", full_qualified_name, "&;\n");
        w!(w, "using inout_type = ", full_qualified_name, "&;\n");
        w!(w, "using ref_type = std::shared_ptr<", full_qualified_name, ">;\n");
        w!(w, "using weak_ref_type = std::weak_ptr<", full_qualified_name, ">;\n");

        if let DefKind::Struct(_) | DefKind::Union(_) | DefKind::Valuetype(_) = &def.kind {
            w!(w, "using sequence_type = std::vector<", qualified_name, ">;\n");
        }

        w!(w, "static const ic_cts::TypeInfo type_info;\n");

        match &def.kind {
            DefKind::Struct(_) => w!(w, "static constexpr bool is_struct = true;\n"),
            DefKind::Union(_) => w!(w, "static constexpr bool is_union = true;\n"),
            DefKind::Enum(enum_ty) => {
                w!(w, "static constexpr bool is_enum = true;\n");
                if let Some(bit_bound) = Self::bit_bound(&def.annotations) {
                    w!(w, "using bit_bound = std::integral_constant<uint32_t, ");
                    self.emit_numeric_value(w, bit_bound, def.id);
                    w!(w, ">;\n");
                    w!(w, "using underlying_type = ", cpp_primitive(enum_ty.ty), ";\n");
                }
            }
            DefKind::Bitmask(bitmask) => {
                w!(w, "static constexpr bool is_bitmask = true;\n");
                w!(w, "using bit_bound = std::integral_constant<uint32_t, ");
                self.emit_numeric_value(
                    w,
                    Self::bit_bound(&def.annotations)
                        .unwrap_or(&Numeric::UInt64((bitmask.ty.size() * 8) as u64)),
                    def.id,
                );
                w!(w, ">;\n");
                w!(w, "using underlying_type = ", cpp_primitive(bitmask.ty), ";\n");
            }
            DefKind::Valuetype(_) => w!(w, "static constexpr bool is_struct = true;\n"),
            _ => {}
        }
        w!(w, "};\n\n");
    }

    pub fn emit_typedef_sequence(&self, w: &mut Twine, def: &Def) {
        let type_name = self.scoped_name(def.id, None);
        w!(w, "using ", def, "Seq = ::std::vector<", type_name, ">;\n\n");
    }

    pub fn emit_hash_declaration(&self, w: &mut Twine, def: &Def) {
        let qualified_name = self.scoped_name(def.id, None);

        w!(w, "template<>\n");
        w!(w, "struct std::hash<", qualified_name, "> {\n");
        w!(w, "using argument_type = ", qualified_name, ";\n");
        w!(w, "using result_type = std::size_t;\n");
        w!(w, self.export_prefix(), "result_type operator()(const argument_type& s) const noexcept;\n");
        w!(w, "};\n\n");
    }

    pub fn emit_hash_implementation(&self, w: &mut Twine, def: &Def) {
        let qualified_name = self.scoped_name(def.id, None);

        let has_members = match &def.kind {
            DefKind::Struct(_) | DefKind::Valuetype(_) | DefKind::Except(_) => {
                !self.collect_all_members(def.id).is_empty()
            }
            DefKind::Union(_) => true,
            _ => false,
        };

        let param = if has_members { " s" } else { "" };
        w!(
            w,
            "std::size_t std::hash<",
            qualified_name,
            ">::operator()(const argument_type&",
            param,
            ") const noexcept {\n"
        );

        if let DefKind::Union(union_ty) = &def.kind {
            self.emit_hash_union(w, union_ty);
        } else if has_members {
            w!(w, "return ::ic_cts::hash_all(\n");
            match &def.kind {
                DefKind::Struct(struct_ty) => {
                    self.emit_hash_struct_members(w, def, &struct_ty.members);
                }
                DefKind::Except(except_ty) => {
                    self.emit_hash_struct_members(w, def, &except_ty.members);
                }
                DefKind::Valuetype(valuetype_ty) => {
                    self.emit_hash_struct_members(w, def, &valuetype_ty.members);
                }
                _ => {}
            }
            w!(w, ");\n");
        } else {
            w!(w, "return 0;\n");
        }

        w!(w, "}\n\n");
    }

    fn emit_hash_struct_members(&self, w: &mut Twine, def: &Def, members: &[Member]) {
        let mut first = true;

        match &def.kind {
            DefKind::Struct(struct_ty) => {
                if let Some(parent) = struct_ty.parent {
                    let parent_name = self.scoped_name(parent.def_id, None);
                    w!(w, "::std::hash<", parent_name, ">()(s)");
                    first = false;
                }
            }
            DefKind::Valuetype(valuetype_ty) => {
                if let Some(parent) = valuetype_ty.parent {
                    let parent_name = self.scoped_name(parent.def_id, None);
                    w!(w, "::std::hash<", parent_name, ">()(s)");
                    first = false;
                }
            }
            _ => {}
        }

        // Hash own members
        for member in members {
            if !first {
                w!(w, ",\n");
            }
            first = false;
            let member_name = format!("s.{}", member.ident.name);
            w!(w, member_name);
        }
        w!(w, "\n");
    }

    fn emit_module(&self, decl_w: &mut Twine, impl_w: &mut Twine, def: &Def, module: &ModuleTy) {
        w!(decl_w, "namespace ", def.ident.name, " {\n");
        decl_w.dedent();
        for &nested_id in &module.definitions {
            self.emit_definition(decl_w, impl_w, nested_id);
        }
        w!(decl_w, "} // namespace ", def.ident.name, "\n\n");
    }

    fn emit_interface(
        &self,
        decl_w: &mut Twine,
        impl_w: &mut Twine,
        def: &Def,
        interface_ty: &InterfaceTy,
    ) {
        let interface_name = &def.ident.name;

        w!(decl_w, "class ", interface_name, " {\n");
        w!(decl_w, "public:\n");

        w!(decl_w, "virtual ~", interface_name, "() = default;\n");

        for &nested_id in &interface_ty.definitions {
            self.emit_definition(decl_w, impl_w, nested_id);
        }

        for prototype in &interface_ty.prototypes {
            self.emit_prototype(decl_w, def, prototype);
        }

        w!(decl_w, "};\n\n");
    }

    fn emit_prototype(&self, w: &mut Twine, interface_def: &Def, proto: &ProtoTy) {
        let method_name = &proto.ident.name;

        let return_ty_str = match &proto.ty.kind {
            TyKind::Primitive(PrimitiveTy::Void) => "void".to_string(),
            _ => self.cpp_type(&proto.ty, interface_def.id),
        };

        w!(w, "virtual ", return_ty_str, " ", method_name, "(\n");

        for (i, param) in proto.params.iter().enumerate() {
            let ty_str = self.cpp_type(&param.ty, interface_def.id);
            let param_name = &param.ident.name;

            let param_mode = match param.kind {
                ParamKind::In => "",
                ParamKind::Out | ParamKind::InOut => "&",
            };

            w!(w, ty_str, param_mode, " a_", param_name);

            if i < proto.params.len() - 1 {
                w!(w, ",\n");
            } else {
                w!(w, "\n");
            }
        }

        w!(w, ") = 0;\n\n");
    }

    fn emit_forward_decl(&self, w: &mut Twine, def: &Def, decl: Decl) {
        match decl {
            Decl::Struct => {
                w!(w, "struct ", def.ident.name, ";\n");
            }
            Decl::Interface | Decl::Valuetype | Decl::Union => {
                w!(w, "class ", def.ident.name, ";\n");
            }
            Decl::Native => {}
        }
    }

    fn emit_definition(&self, decl_w: &mut Twine, impl_w: &mut Twine, def_id: DefId) {
        let def = self.hir.context.definitions.get(def_id);

        match &def.kind {
            DefKind::Module(module) => self.emit_module(decl_w, impl_w, def, module),
            DefKind::Struct(struct_ty) => self.emit_struct(decl_w, impl_w, def, struct_ty),
            DefKind::Except(except_ty) => self.emit_exception(decl_w, impl_w, def, except_ty),
            DefKind::Union(union_ty) => self.emit_union(decl_w, impl_w, def, union_ty),
            DefKind::Enum(enum_ty) => self.emit_enum(decl_w, impl_w, def, enum_ty),
            DefKind::Bitmask(bitmask_ty) => self.emit_bitmask(decl_w, impl_w, def, bitmask_ty),
            DefKind::Const(const_ty) => self.emit_const(decl_w, def, const_ty),
            DefKind::Alias(alias_ty) => self.emit_typedef(decl_w, def, alias_ty),
            DefKind::Interface(interface_ty) => {
                self.emit_interface(decl_w, impl_w, def, interface_ty);
            }
            DefKind::Valuetype(valuetype_ty) => {
                self.emit_valuetype(decl_w, impl_w, def, valuetype_ty);
            }
            DefKind::Decl(decl) => self.emit_forward_decl(decl_w, def, *decl),
            _ => {}
        }
    }

    fn emit_cpp_definition(&self, w: &mut Twine, def_id: DefId) {
        let def = self.hir.context.definitions.get(def_id);

        match &def.kind {
            DefKind::Module(module) => {
                for &nested_id in &module.definitions {
                    self.emit_cpp_definition(w, nested_id);
                }
            }
            DefKind::Interface(interface) => {
                for &nested_id in &interface.definitions {
                    self.emit_cpp_definition(w, nested_id);
                }
            }
            DefKind::Valuetype(valuetype) => {
                for &nested_id in &valuetype.definitions {
                    self.emit_cpp_definition(w, nested_id);
                }
                self.emit_hash_implementation(w, def);
                self.emit_member_info(w, def);
                self.emit_type_info_definition(w, def);
            }
            DefKind::Struct(_) | DefKind::Union(_) => {
                self.emit_hash_implementation(w, def);
                self.emit_member_info(w, def);
                self.emit_type_info_definition(w, def);
            }
            DefKind::Enum(_) | DefKind::Bitmask(_) => {
                self.emit_member_info(w, def);
                self.emit_type_info_definition(w, def);
            }
            DefKind::Except(_) => {
                self.emit_hash_implementation(w, def);
            }
            _ => {}
        }
    }

    fn output_extension(&self) -> &str {
        self.options.header_ext.as_deref().unwrap_or("h")
    }

    fn output_filename(&self, file_id: FileId, extension: &str) -> String {
        let source_path = self.source_map.name(file_id);
        let output_file = source_path.with_extension(extension);
        output_file
            .file_name()
            .and_then(|s| s.to_str())
            .unwrap()
            .to_string()
    }

    fn build_path(&self, file_name: &str) -> String {
        if let Some(subfolder) = &self.options.header_subdir {
            format!("{subfolder}/{file_name}").replace('\\', "/")
        } else {
            file_name.replace('\\', "/")
        }
    }

    pub fn generate(&self) -> Vec<File> {
        let mut files_map: HashMap<FileId, Vec<DefId>> = HashMap::new();

        for &def_id in &self.hir.order {
            let def = self.hir.context.definitions.get(def_id);
            let file_id = def.ident.span.start.file_id;
            files_map.entry(file_id).or_default().push(def_id);
        }

        let mut result = Vec::new();
        for (file_id, def_ids) in files_map {
            let mut header = Twine::new();
            let mut decls = Twine::new();
            let mut impls = Twine::new();
            let mut cpp_impls = Twine::new();

            self.emit_generated_header(&mut header);
            w!(header, "#pragma once\n\n");
            w!(header, "#include <array>\n");
            w!(header, "#include <cstdint>\n");
            w!(header, "#include <map>\n");
            w!(header, "#include <memory>\n");
            w!(header, "#include <optional>\n");
            w!(header, "#include <string>\n");
            w!(header, "#include <vector>\n\n");
            w!(header, "#include <ic_cts/any.h>\n");
            w!(header, "#include <ic_cts/member_info.h>\n");
            w!(header, "#include <ic_cts/memory.h>\n");

            let mut dependencies = std::collections::HashSet::new();
            for &def_id in &def_ids {
                collect_def_dependencies(self.hir, def_id, file_id, &mut dependencies);
            }

            let mut deps_vec: Vec<FileId> = dependencies.into_iter().collect();
            deps_vec.sort();

            for &dep_file_id in &deps_vec {
                let dep_file_name = self.output_filename(dep_file_id, self.output_extension());
                let include_path = self.build_path(&dep_file_name);
                w!(header, "\n#include \"", include_path, "\"");
            }

            if !deps_vec.is_empty() {
                w!(header, "\n");
            }

            w!(header, "\n");

            for def_id in &def_ids {
                self.emit_definition(&mut decls, &mut impls, *def_id);
            }

            let output_file_name = self.output_filename(file_id, self.output_extension());

            let mut header_content = header.finish();
            header_content.push_str(&decls.finish());
            header_content.push_str(&impls.finish());

            let header_path = self.build_path(&output_file_name);
            result.push(File::Generated {
                path: PathBuf::from(&header_path),
                source: header_content,
            });

            self.emit_generated_header(&mut cpp_impls);
            w!(cpp_impls, "#include \"", header_path, "\"\n\n");
            w!(cpp_impls, "#include <ic_cts/dds_xtypes_constants.h>\n");
            w!(cpp_impls, "#include <ic_cts/hash.h>\n\n");

            for def_id in &def_ids {
                self.emit_cpp_definition(&mut cpp_impls, *def_id);
            }

            let cpp_content = cpp_impls.finish();
            let cpp_file_name = self.output_filename(file_id, "cpp");
            result.push(File::Generated {
                path: PathBuf::from(cpp_file_name),
                source: cpp_content,
            });
        }
        result
    }
}

pub(crate) fn cpp_primitive(prim: PrimitiveTy) -> &'static str {
    match prim {
        PrimitiveTy::Void => "void",
        PrimitiveTy::Bool => "bool",
        PrimitiveTy::Char => "char",
        PrimitiveTy::WChar => "char16_t",
        PrimitiveTy::Int8 => "int8_t",
        PrimitiveTy::UInt8 => "uint8_t",
        PrimitiveTy::Int16 => "int16_t",
        PrimitiveTy::UInt16 => "uint16_t",
        PrimitiveTy::Int32 => "int32_t",
        PrimitiveTy::UInt32 => "uint32_t",
        PrimitiveTy::Int64 => "int64_t",
        PrimitiveTy::UInt64 => "uint64_t",
        PrimitiveTy::Float32 => "float",
        PrimitiveTy::Float64 => "double",
        PrimitiveTy::Float128 => "long double",
    }
}

fn write_escaped_char<W: Write>(w: &mut W, c: char) -> std::fmt::Result {
    match c {
        '\0' => w.write_str("\\0"),
        '\x07' => w.write_str("\\a"),
        '\x08' => w.write_str("\\b"),
        '\t' => w.write_str("\\t"),
        '\n' => w.write_str("\\n"),
        '\x0B' => w.write_str("\\v"),
        '\x0C' => w.write_str("\\f"),
        '\r' => w.write_str("\\r"),
        '"' => w.write_str("\\\""),
        '\'' => w.write_str("\\'"),
        '\\' => w.write_str("\\\\"),
        '?' => w.write_str("\\?"),

        c if c.is_ascii_graphic() || c == ' ' => w.write_char(c),

        c => {
            let code = c as u32;
            if code <= 0xFFFF {
                write!(w, "\\u{code:04X}")
            } else {
                write!(w, "\\U{code:08X}")
            }
        }
    }
}

fn escape_char(w: &mut Twine, c: char) {
    if !c.is_ascii() {
        w!(w, "u");
    }

    w!(w, "'");
    _ = write_escaped_char(w, c);
    w!(w, "'");
}

pub(crate) fn emit_escaped_string(w: &mut Twine, s: &str) {
    w!(w, '"');
    for c in s.chars() {
        _ = write_escaped_char(w, c);
    }
    w!(w, '"');
}
