// Copyright 2026 KONGSBERG
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions are met:
//
// 1. Redistributions of source code must retain the above copyright notice,
//    this list of conditions and the following disclaimer.
//
// 2. Redistributions in binary form must reproduce the above copyright notice,
//    this list of conditions and the following disclaimer in the documentation
//    and/or other materials provided with the distribution.
//
// 3. Neither the name of the copyright holder nor the names of its contributors
//    may be used to endorse or promote products derived from this software
//    without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
// ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
// WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
// DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
// FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
// DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
// SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
// CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
// OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
// OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

use std::collections::{BTreeSet, HashMap};
use std::path::PathBuf;

use ic_emit::File;
use ic_emit::printer::{Twine, w};
use ic_hir::ResolvedGraph;
use ic_hir::hir::{
    AliasTy, Attribute, BitmaskTy, ConstTy, Def, DefFlags, DefId, DefKind, EnumTy, InterfaceTy,
    Member, Numeric, ParamKind, Parameter, PrimitiveTy, ProtoTy, Ty, TyKind, UnionTy, ValueTy,
};
use ic_vfs::SourceMap;

use crate::deps::collect_file_dependencies;

pub struct CGen<'a> {
    hir: &'a ResolvedGraph,
    source_map: &'a SourceMap,
}

impl<'a> CGen<'a> {
    pub fn new(hir: &'a ResolvedGraph, source_map: &'a SourceMap) -> Self {
        Self { hir, source_map }
    }

    fn emit_header(w: &mut Twine) {
        const VERSION: &str = env!("CARGO_PKG_VERSION");
        w!(w, "// @generated by ic-idl ", VERSION, "\n\n");
    }

    fn primitive_type(primitive: PrimitiveTy) -> &'static str {
        match primitive {
            PrimitiveTy::Void => "void",
            PrimitiveTy::Bool => "bool",
            PrimitiveTy::Char => "char",
            PrimitiveTy::WChar => "char16_t",
            PrimitiveTy::Int8 => "int8_t",
            PrimitiveTy::UInt8 => "uint8_t",
            PrimitiveTy::Int16 => "int16_t",
            PrimitiveTy::UInt16 => "uint16_t",
            PrimitiveTy::Int32 => "int32_t",
            PrimitiveTy::UInt32 => "uint32_t",
            PrimitiveTy::Int64 => "int64_t",
            PrimitiveTy::UInt64 => "uint64_t",
            PrimitiveTy::Float32 => "float",
            PrimitiveTy::Float64 => "double",
            PrimitiveTy::Float128 => "long double",
        }
    }

    fn c_type(&self, ty: &Ty) -> String {
        match &ty.kind {
            TyKind::Primitive(primitive) => Self::primitive_type(*primitive).to_string(),
            TyKind::String { wide, .. } => {
                if *wide {
                    "const char16_t*".to_string()
                } else {
                    "const char*".to_string()
                }
            }
            TyKind::Adt(def_id) => self.hir.context.type_of(*def_id).to_string(),
            TyKind::Array { ty, .. } => format!("{}*", self.c_type(ty)),
            TyKind::Sequence { .. } => "idl_sequence_t*".to_string(),
            TyKind::Map { .. } => "idl_map_t*".to_string(),
            TyKind::Any => "idl_any_t*".to_string(),
            TyKind::Fixed => "long double".to_string(),
            TyKind::Null => "void".to_string(),
        }
    }

    fn c_member(&self, ty: &Ty, name: impl std::fmt::Display) -> String {
        match &ty.kind {
            TyKind::Array { ty, len, .. } => self.c_member(ty, format!("{name}[{len}]")),
            _ => format!("{} {name}", self.c_type(ty)),
        }
    }

    fn is_optional(&self, member: &Member) -> bool {
        member.annotations.iter().any(|ann| {
            if let Some(def_id) = ann.def_id {
                let def = self.hir.context.type_of(def_id);
                def.flags.contains(DefFlags::IS_BUILTIN) && def.ident.name == "optional"
            } else {
                false
            }
        })
    }

    fn is_pointer_type(&self, ty: &Ty) -> bool {
        match &ty.kind {
            TyKind::String { .. } | TyKind::Sequence { .. } | TyKind::Map { .. } | TyKind::Any => {
                true
            }
            TyKind::Adt(def_id) => match &self.hir.context.type_of(*def_id).kind {
                DefKind::Alias(alias) => self.is_pointer_type(&alias.ty),
                _ => false,
            },
            _ => false,
        }
    }

    fn c_optional_member(&self, ty: &Ty, name: impl std::fmt::Display) -> String {
        if self.is_pointer_type(ty) {
            return self.c_member(ty, name);
        }

        match &ty.kind {
            TyKind::Array { ty, len, .. } => self.c_member(ty, format!("(*{name})[{len}]")),
            _ => self.c_member(ty, format!("*{name}")),
        }
    }

    fn emit_member(&self, w: &mut Twine, member: &Member) {
        let declaration = if self.is_optional(member) {
            self.c_optional_member(&member.ty, &member.ident.name)
        } else {
            self.c_member(&member.ty, &member.ident.name)
        };
        w!(w, declaration, ";\n");
    }

    fn is_scalar(&self, ty: &Ty) -> bool {
        match &ty.kind {
            TyKind::Primitive(_) | TyKind::String { .. } | TyKind::Fixed => true,
            TyKind::Adt(def_id) => match &self.hir.context.base_def_of(*def_id).kind {
                DefKind::Alias(alias) => self.is_scalar(&alias.ty),
                DefKind::Enum(_) | DefKind::Bitmask(_) => true,
                _ => false,
            },
            TyKind::Array { .. }
            | TyKind::Sequence { .. }
            | TyKind::Map { .. }
            | TyKind::Any
            | TyKind::Null => false,
        }
    }

    fn c_input_type(&self, ty: &Ty) -> String {
        if self.is_scalar(ty) {
            return self.c_type(ty);
        }

        match &ty.kind {
            TyKind::Sequence { .. } | TyKind::Map { .. } | TyKind::Any => {
                format!("const {}", self.c_type(ty))
            }
            _ => format!("const {}*", self.c_type(ty)),
        }
    }

    fn c_output_type(&self, ty: &Ty) -> String {
        format!("{}*", self.c_type(ty))
    }

    fn c_parameter(&self, parameter: &Parameter) -> String {
        let ty = match parameter.kind {
            ParamKind::In => self.c_input_type(&parameter.ty),
            ParamKind::Out | ParamKind::InOut => self.c_output_type(&parameter.ty),
        };

        format!("{ty} {}", parameter.ident.name)
    }

    fn format_numeric(&self, value: &Numeric) -> String {
        match value {
            Numeric::Bool(value) => if *value { "true" } else { "false" }.to_string(),
            Numeric::Int8(value) => format!("INT8_C({value})"),
            Numeric::UInt8(value) => format!("UINT8_C({value})"),
            Numeric::Int16(value) => format!("INT16_C({value})"),
            Numeric::UInt16(value) => format!("UINT16_C({value})"),
            Numeric::Int32(value) => format!("INT32_C({value})"),
            Numeric::UInt32(value) => format!("UINT32_C({value})"),
            Numeric::Int64(i64::MIN) => "INT64_MIN".to_string(),
            Numeric::Int64(value) if *value < 0 => format!("(-INT64_C({}))", value.unsigned_abs()),
            Numeric::Int64(value) => format!("INT64_C({value})"),
            Numeric::UInt64(value) => format!("UINT64_C({value})"),
            Numeric::Const(def_id) => self.hir.context.type_of(*def_id).to_string(),
            Numeric::Char(value) => format!("'{}'", value.escape_default()),
            Numeric::WChar(value) => format!("u'{}'", value.escape_default()),
            Numeric::Float(value) => format!("{value}F"),
            Numeric::Double(value) => value.to_string(),
            Numeric::String(value) => format!("\"{}\"", value.escape_default()),
            Numeric::WString(value) => format!("u\"{}\"", value.escape_default()),
            Numeric::Array { values, .. } => {
                let values = values
                    .iter()
                    .map(|value| self.format_numeric(value))
                    .collect::<Vec<_>>()
                    .join(", ");

                format!("{{{values}}}")
            }
            Numeric::Null
            | Numeric::Sequence { .. }
            | Numeric::Map { .. }
            | Numeric::Struct { .. }
            | Numeric::Union { .. } => "0".to_string(),
        }
    }

    fn emit_struct(&self, w: &mut Twine, def: &Def, members: &[Member], parent: Option<DefId>) {
        w!(w, "typedef struct ", def, " {\n");

        if let Some(parent) = parent {
            let parent = self.hir.context.type_of(parent);
            w!(w, parent, " base;\n");
        }

        for member in members {
            self.emit_member(w, member);
        }

        if parent.is_none() && members.is_empty() {
            w!(w, "uint8_t _reserved;\n");
        }

        w!(w, "} ", def, ";\n\n");
    }

    fn emit_union(&self, w: &mut Twine, def: &Def, union_ty: &UnionTy) {
        w!(w, "typedef struct ", def, " {\n");
        w!(w, self.c_member(&union_ty.disc.ty, "_d"), ";\n");

        w!(w, "union {\n");
        for variant in &union_ty.variants {
            if !matches!(variant.ty.kind, TyKind::Null) {
                w!(w, self.c_member(&variant.ty, &variant.ident.name), ";\n");
            }
        }
        w!(w, "} value;\n");
        w!(w, "} ", def, ";\n\n");
    }

    fn emit_prototype(&self, w: &mut Twine, proto: &ProtoTy) {
        w!(w, "idl_status_t (*", proto.ident.name, ")(\n");
        w!(w, "void*,\n");

        for parameter in &proto.params {
            w!(w, self.c_parameter(parameter), ",\n");
        }

        if !matches!(
            proto.ty.kind,
            TyKind::Primitive(PrimitiveTy::Void) | TyKind::Null
        ) {
            w!(w, self.c_output_type(&proto.ty), ",\n");
        }

        w!(w, "idl_error_t*\n");
        w!(w, ");\n");
    }

    fn emit_attribute(&self, w: &mut Twine, attribute: &Attribute) {
        w!(w, "idl_status_t (*get_", attribute.ident.name, ")(\n");
        w!(w, "void*,\n");
        w!(w, self.c_output_type(&attribute.ty), ",\n");
        w!(w, "idl_error_t*\n");
        w!(w, ");\n");

        if !attribute.is_readonly {
            w!(w, "idl_status_t (*set_", attribute.ident.name, ")(\n");
            w!(w, "void*,\n");
            w!(w, self.c_input_type(&attribute.ty), ",\n");
            w!(w, "idl_error_t*\n");
            w!(w, ");\n");
        }
    }

    fn emit_interface(&self, w: &mut Twine, def: &Def, interface_ty: &InterfaceTy) {
        w!(w, "typedef struct ", def, " {\n");

        for parent in &interface_ty.parents {
            let parent = self.hir.context.type_of(parent.def_id);
            w!(w, parent, " ", parent, "_base;\n");
        }

        for prototype in &interface_ty.prototypes {
            self.emit_prototype(w, prototype);
        }

        for attribute in &interface_ty.attributes {
            self.emit_attribute(w, attribute);
        }

        if interface_ty.parents.is_empty()
            && interface_ty.prototypes.is_empty()
            && interface_ty.attributes.is_empty()
        {
            w!(w, "uint8_t _reserved;\n");
        }

        w!(w, "} ", def, ";\n\n");
    }

    fn emit_valuetype(&self, w: &mut Twine, def: &Def, value_ty: &ValueTy) {
        w!(w, "typedef struct ", def, " {\n");

        if let Some(parent) = value_ty.parent {
            let parent = self.hir.context.type_of(parent.def_id);
            w!(w, parent, " ", parent, "_base;\n");
        }

        if let Some(supports) = value_ty.supports {
            let supports = self.hir.context.type_of(supports.def_id);
            w!(w, supports, " ", supports, "_base;\n");
        }

        for member in &value_ty.members {
            self.emit_member(w, member);
        }

        for prototype in &value_ty.prototypes {
            self.emit_prototype(w, prototype);
        }

        for attribute in &value_ty.attributes {
            self.emit_attribute(w, attribute);
        }

        if value_ty.parent.is_none()
            && value_ty.supports.is_none()
            && value_ty.members.is_empty()
            && value_ty.prototypes.is_empty()
            && value_ty.attributes.is_empty()
        {
            w!(w, "uint8_t _reserved;\n");
        }

        w!(w, "} ", def, ";\n\n");
    }

    fn emit_alias(&self, w: &mut Twine, def: &Def, alias: &AliasTy) {
        w!(w, "typedef ", self.c_member(&alias.ty, def), ";\n\n");
    }

    fn emit_const(&self, w: &mut Twine, def: &Def, const_ty: &ConstTy) {
        let value = self.format_numeric(&const_ty.value);
        if matches!(const_ty.value, Numeric::String(_) | Numeric::WString(_)) {
            w!(w, "#define ", def, " ", value, "\n\n");
        } else {
            w!(w, "#define ", def, " ((", self.c_type(&const_ty.ty), ")", value, ")\n\n");
        }
    }

    fn emit_decl(w: &mut Twine, def: &Def) {
        w!(w, "typedef struct ", def, " ", def, ";\n\n");
    }

    fn emit_enum(&self, w: &mut Twine, def: &Def, enum_ty: &EnumTy) {
        let primitive = Self::primitive_type(enum_ty.ty);
        w!(w, "typedef ", primitive, " ", def, ";\n\n");

        for &field_id in &enum_ty.fields {
            let field = self.hir.context.type_of(field_id);
            if let DefKind::Const(const_ty) = &field.kind {
                let value = self.format_numeric(&const_ty.value);
                w!(w, "#define ", field, " ((", def, ")", value, ")\n");
            }
        }
        w!(w, "\n");
    }

    fn emit_bitmask(&self, w: &mut Twine, def: &Def, bitmask_ty: &BitmaskTy) {
        let primitive = Self::primitive_type(bitmask_ty.ty);
        w!(w, "typedef ", primitive, " ", def, ";\n\n");

        for &flag_id in &bitmask_ty.flags {
            let flag = self.hir.context.type_of(flag_id);
            if let DefKind::Const(const_ty) = &flag.kind {
                let value = self.hir.context.unsigned_value(&const_ty.value);
                w!(w, "#define ", flag, " ((", def, ")", value, ")\n");
            }
        }

        w!(w, "\n");
    }

    fn emit_definition(&self, w: &mut Twine, def_id: DefId) {
        let def = self.hir.context.type_of(def_id);

        match &def.kind {
            DefKind::Struct(struct_ty) => self.emit_struct(
                w,
                def,
                &struct_ty.members,
                struct_ty.parent.map(|parent| parent.def_id),
            ),
            DefKind::Union(union_ty) => self.emit_union(w, def, union_ty),
            DefKind::Except(except_ty) => self.emit_struct(w, def, &except_ty.members, None),
            DefKind::Interface(interface_ty) => self.emit_interface(w, def, interface_ty),
            DefKind::Valuetype(value_ty) => self.emit_valuetype(w, def, value_ty),
            DefKind::Alias(alias) => self.emit_alias(w, def, alias),
            DefKind::Const(const_ty) => self.emit_const(w, def, const_ty),
            DefKind::Enum(enum_ty) => self.emit_enum(w, def, enum_ty),
            DefKind::Bitmask(bitmask_ty) => self.emit_bitmask(w, def, bitmask_ty),
            DefKind::Decl(_) => Self::emit_decl(w, def),
            _ => {}
        }
    }

    pub fn generate(&self) -> Vec<File> {
        let mut files = HashMap::<_, Vec<_>>::new();
        for &def_id in &self.hir.order {
            let def = self.hir.context.type_of(def_id);
            let file_id = def.ident.span.start.file_id;
            files.entry(file_id).or_default().push(def_id);
        }

        let mut files: Vec<_> = files.into_iter().collect();
        files.sort_by_key(|(file_id, _)| self.source_map.name(*file_id).to_path_buf());

        let mut result = vec![];
        for (file_id, def_ids) in files {
            let path = self.source_map.name(file_id).with_extension("h");
            let file_name = path.file_name().and_then(|name| name.to_str()).unwrap();

            let mut w = Twine::with_indent(4);
            Self::emit_header(&mut w);
            w!(w, "#pragma once\n\n");
            w!(w, "#include <stdbool.h>\n");
            w!(w, "#include <stdint.h>\n");
            w!(w, "#include <ic_idl/runtime.h>\n");

            let mut dependencies = BTreeSet::new();
            for &def_id in &def_ids {
                collect_file_dependencies(self.hir, def_id, file_id, &mut dependencies);
            }

            for dependency in dependencies {
                let dependency_name = self
                    .source_map
                    .name(dependency)
                    .with_extension("h")
                    .file_name()
                    .and_then(|name| name.to_str())
                    .unwrap()
                    .to_string();

                w!(w, "#include \"", dependency_name, "\"\n");
            }
            w!(w, "\n");

            w!(w, "#ifdef __cplusplus\n");
            w!(w, "extern \"C\" {\n");
            w.dedent();
            w!(w, "#endif\n\n");

            for def_id in def_ids {
                self.emit_definition(&mut w, def_id);
            }

            w!(w, "#ifdef __cplusplus\n");
            w.indent();
            w!(w, "}\n");
            w!(w, "#endif\n");

            result.push(File::Generated {
                path: PathBuf::from(file_name),
                source: w.finish(),
            });
        }

        result
    }
}
