// Copyright 2024 KONGSBERG
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions are met:
//
// 1. Redistributions of source code must retain the above copyright notice,
//    this list of conditions and the following disclaimer.
//
// 2. Redistributions in binary form must reproduce the above copyright notice,
//    this list of conditions and the following disclaimer in the documentation
//    and/or other materials provided with the distribution.
//
// 3. Neither the name of the copyright holder nor the names of its contributors
//    may be used to endorse or promote products derived from this software
//    without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS “AS IS” AND
// ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
// WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
// DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
// FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
// DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
// SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
// CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
// OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
// OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

module annotation_typedef {
    @optional typedef string MyTypedef1;
    typedef @optional string MyTypedef2;
    typedef string @optional MyTypedef3;
    typedef string MyTypedef4 @optional;
};

module annotation_struct {
    @nested struct MyStruct1 {};
    struct @nested MyStruct2 {};
    struct MyStruct3 @nested {};
    struct MyStruct4 {} @nested;

    struct MyStruct5 {
        @default(5) int32 value;
    };

    struct MyStruct6 {
        int32 @default(5) value;
    };

    struct MyStruct7 {
        int32 value @default(5);
    };
};

module annotation_union {
    @nested union MyUnion1 switch(octet) {
    default:
        null;
    };

    union @nested MyUnion1 switch(octet) {
    default:
        null;
    };

    union MyUnion2 @nested switch(octet) {
    default:
        null;
    };

    union MyUnion3 switch(@default(3) octet) {
    default:
        null;
    };

    union MyUnion4 switch(octet) {
    default:
        @default(5) int32 value;
    };

    union MyUnion5 switch(octet) {
    default:
        int32 @default(5) value;
    };

    union MyUnion6 switch(octet) {
    default:
        int32 value @default(5);
    };
};
