# Copyright 2024 KONGSBERG
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice,
#    this list of conditions and the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above copyright notice,
#    this list of conditions and the following disclaimer in the documentation
#    and/or other materials provided with the distribution.
#
# 3. Neither the name of the copyright holder nor the names of its contributors
#    may be used to endorse or promote products derived from this software
#    without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS “AS IS” AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
# OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

default:
  image: "alpine:3.19"
  before_script:
    - mkdir -p /usr/local/share/ca-certificates
    - cp /etc/gitlab-runner/certs/ca.crt /usr/local/share/ca-certificates/gitlab-runner.crt
    - cat /etc/gitlab-runner/certs/ca.crt >> /etc/ssl/certs/ca-certificates.crt
    - apk update
    - apk add ca-certificates rustup cmake clang mold git gcc g++ samurai flex bison musl-dev
    - update-ca-certificates
    - rustup-init --profile minimal -y
    - source $HOME/.cargo/env
  tags:
    - linux
    - internet

stages:
  - lint
  - build
  - test

lint:rustfmt:
  stage: lint
  needs: []
  script:
    - rustup toolchain install nightly -c rustfmt
    - cargo +nightly fmt -- --check

lint:clippy:
  stage: lint
  needs: []
  script:
    - rustup component add clippy
    - cargo clippy --workspace -- -Dwarnings

lint:license:
  stage: lint
  needs: []
  script:
    - cargo xtask deny

lint:ipr:
  stage: lint
  needs: []
  script:
    - cargo xtask ipr

build:stable:
  stage: build
  needs: []
  script:
    - rustc --version && cargo --version
    - cargo xtask bootstrap
    - cargo install --path crates/ic-driver --root install
  artifacts:
    paths:
      - "install/bin/"

test:stable:
  stage: test
  needs: []
  script:
    - cargo test --workspace
  dependencies:
    - build:stable