# Copyright 2024 KONGSBERG
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice,
#    this list of conditions and the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above copyright notice,
#    this list of conditions and the following disclaimer in the documentation
#    and/or other materials provided with the distribution.
#
# 3. Neither the name of the copyright holder nor the names of its contributors
#    may be used to endorse or promote products derived from this software
#    without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
# OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

[workspace]
resolver = "3"
members = [
    "crates/ic-alloc",
    "crates/ic-cli",
    "crates/ic-cli-derive",
    "crates/ic-codegen-cpp",
    "crates/ic-codegen-csharp",
    "crates/ic-codegen-idl",
    "crates/ic-codegen-java",
    "crates/ic-codegen-json",
    "crates/ic-codegen-json-schema",
    "crates/ic-codegen-protobuf",
    "crates/ic-codegen-python",
    "crates/ic-codegen-rust",
    "crates/ic-codegen-typescript",
    "crates/ic-codegen-xml",
    "crates/ic-diagnostic",
    "crates/ic-emit",
    "crates/ic-expr",
    "crates/ic-fuzz",
    "crates/ic-hir",
    "crates/ic-hir-lower",
    "crates/ic-hir-tree",
    "crates/ic-hir-xform",
    "crates/ic-idl",
    "crates/ic-lexer",
    "crates/ic-lint",
    "crates/ic-parse",
    "crates/ic-preproc",
    "crates/ic-syntax",
    "crates/ic-vfs",
    "crates/xtask",
]
exclude = ["crates/ic-parse/fuzz"]
default-members = ["crates/ic-idl"]

[workspace.package]
version = "0.5.9"
rust-version = "1.92"
publish = false
authors = ["KONGSBERG <DDS-InterCOM@kda.kongsberg.com>"]

[workspace.dependencies]
criterion = "0.8"
proc-macro2 = "1.0.106"
quote = "1.0.45"
syn = "2.0.117"
tracing = "0.1.44"
intercom-cts = { path = "runtime/rust/intercom-cts", features = ["derive"] }

[workspace.lints.rust]
future_incompatible = "deny"
nonstandard_style = "warn"

[workspace.lints.clippy]
all = { level = "warn", priority = -1 }
pedantic = { level = "warn", priority = -1 }
cargo = { level = "warn", priority = -1 }

# We don't want to use these in production code
undocumented_unsafe_blocks = "warn"
todo = "warn"
dbg_macro = "warn"

# Only the main `ic-idl` crate is allowed to use stdio
print_stdout = "warn"
print_stderr = "warn"

# Disable some annoying style lints
module_name_repetitions = "allow"
struct_excessive_bools = "allow"
ignored_unit_patterns = "allow"
struct_field_names = "allow"
ignore_without_reason = "allow"
multiple_crate_versions = "allow"
missing_errors_doc = "allow"
chunks_exact_to_as_chunks = "allow"

[profile.release]
lto = "thin"
codegen-units = 1

# Keep symbol information for now
strip = "debuginfo"
