// Copyright 2026 KONGSBERG
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions are met:
//
// 1. Redistributions of source code must retain the above copyright notice,
//    this list of conditions and the following disclaimer.
//
// 2. Redistributions in binary form must reproduce the above copyright notice,
//    this list of conditions and the following disclaimer in the documentation
//    and/or other materials provided with the distribution.
//
// 3. Neither the name of the copyright holder nor the names of its contributors
//    may be used to endorse or promote products derived from this software
//    without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
// ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
// WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
// DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
// FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
// DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
// SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
// CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
// OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
// OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

@nested
struct SomeData {
    string str;
    sequence<octet> data;
};

@nested
struct SomeOtherData {
    int32 id;
    SomeData data;
};

union ComplexUnion switch(uint32) {
case 0:
    SomeData my_data;
case 1:
    string my_str;
case 2:
    int32 my_int;
default:
    SomeOtherData my_other_data;
};

struct WrapsComplexUnion {
    string name;
    float coords;
    ComplexUnion data;
};

union RecursiveUnion;

struct WrapsRecursiveUnion {
    @external RecursiveUnion data;
};

union RecursiveUnion switch(octet) {
case 1:
    WrapsRecursiveUnion recursive_union;
};

struct CorbaKw {
    any any_value;
    Object obj_value;
    string str_value;
};

struct LargeCopyArrays {
    octet one_dim[128];
    octet two_dim[128][128];
    octet three_dim[128][128][128];
};

struct LargeCloneArrays {
    string one_dim[64];
    string two_dim[64][64];
    string three_dim[64][64][64];
};

const string LARGE_STRING_ARRAY[45] = {
    "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0",
    "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0",
    "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0"
};

const string LARGE_MULTI_DIM_STRING_ARRAY[3][15] = {
    {"0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0"},
    {"0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0"},
    {"0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0", "0"}
};

struct SingleCopyArray {
    octet one_dim[128];
};

struct SingleCloneArray {
    string one_dim[128];
};
