// Copyright 2026 KONGSBERG
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions are met:
//
// 1. Redistributions of source code must retain the above copyright notice,
//    this list of conditions and the following disclaimer.
//
// 2. Redistributions in binary form must reproduce the above copyright notice,
//    this list of conditions and the following disclaimer in the documentation
//    and/or other materials provided with the distribution.
//
// 3. Neither the name of the copyright holder nor the names of its contributors
//    may be used to endorse or promote products derived from this software
//    without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
// ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
// WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
// DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
// FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
// DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
// SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
// CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
// OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
// OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

const string STR1 = "STR1";
const string STR2 = "STR2";

typedef boolean MyArray[1][2][3];
typedef map<string, int32> MyMap;

const MyArray MY_ARR = {{{false, true, false}, {true, false, true}}};

struct X {
    boolean bool_empty;
    @default(true) boolean bool_default;

    int32 int32_empty;
    @default(5) int32 int32_default;

    float float_empty;
    @default(0.75) float float_default;

    string string_empty;
    @default("test") string string_default;
    @default(STR1) string string_const_default;
    @shared string string_shared_empty;
    @shared @default(STR1) string string_shared_default;

    @optional int32 optional_empty;

    int32 array_empty[2];
    @default({123, 456}) int32 array_default[2];

    sequence<string> string_seq_empty;
    @default({"abc", "def"}) sequence<string> string_seq_default;

    sequence<string> string_seq_array_empty[2];
    @default({{"abc"}, {"def"}}) sequence<string> string_seq_array_default[2];

    sequence<string> string_seq_const_empty;
    @default({STR1, STR2}) sequence<string> string_seq_const_default;

    map<int32, int32> primitive_map_empty;
    @default({{1, 2}, {3, 4}, {5, 6}, {7, 8}, {9, 0}})
    map<int32, int32> primitive_map_default;

    map<int32, int32> string_map_empty;
    @default({{"key1", "value1"}, {"key2", "value2"}})
    map<string, string> string_map_default;

    MyMap my_map;

    sequence<MyArray> complex_array_seq_empty;
    @default({
        {{{false, false, false}, {true, false, false}}},
        {{{false, true, false}, {false, false, true}}}
    })
    sequence<MyArray> complex_array_seq_default;
};

enum MyDefaultEnum {
    ONE = 1,
    @default_literal TWO,
    NINE = 9
};

const MyDefaultEnum MY_ENUM_CONST = MyDefaultEnum::NINE;

union UnionSharedDefault switch(@default(1) octet) {
case 1:
    @default(5) @shared int32 my_int;
};

union UnionDefaultCase switch(octet) {
case 1:
    int32 my_int;
default:
    string fallback;
};

struct Test {
    int32 my_int;
    string my_str;
    float my_float;
};

const Test MY_TEST = {123, "test", 1.5};

struct ContainsTest {
    Test my_test;
    int32 other_int;
};

const ContainsTest MY_CONTAINS_TEST = {{123, "abc", 3.0}, 456};

module my_bitmask_mod {
bitmask MyBitmask {
    ONE = 1
};

const MyBitmask MY_CONST = ONE;
const MyBitmask MY_OTHER_CONST = MY_CONST;

@nested
struct HasBitmaskConstDefValue {
    @default(MY_OTHER_CONST) MyBitmask my_bitmask_value;
};
};

module referential {
    struct Foo {
        string value;
    };

    struct Bar {
        Foo my_foo;
    };

    const Foo MY_FOO = {"foo"};

    // Refers to another instance of Lazy<>, so the generated code must deref
    // and clone the inner value
    const Bar MY_BAR = {MY_FOO};
};
