// Copyright 2026 KONGSBERG
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions are met:
//
// 1. Redistributions of source code must retain the above copyright notice,
//    this list of conditions and the following disclaimer.
//
// 2. Redistributions in binary form must reproduce the above copyright notice,
//    this list of conditions and the following disclaimer in the documentation
//    and/or other materials provided with the distribution.
//
// 3. Neither the name of the copyright holder nor the names of its contributors
//    may be used to endorse or promote products derived from this software
//    without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
// ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
// WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
// DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
// FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
// DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
// SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
// CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
// OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
// OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

module dynamic {
    @nested
    struct Foob {
        boolean my_bool;
    };

    @nested
    struct Nested {
        octet my_nested_octet;
    };

    enum PlainEnum {
        PLAIN_FOO = -1,
        PLAIN_BAR = 0,
        PLAIN_BAZ = 3
    };

    @nested
    struct PlainStruct {
        boolean my_bool;
        int8 my_int8;
        uint8 my_uint8;
        int16 my_int16;
        uint16 my_uint16;
        int32 my_int32;
        uint32 my_uint32;
        int64 my_int64;
        uint64 my_uint64;
        float my_float;
        double my_double;
        char my_char;
        wchar my_wchar;
    };

    @nested
    struct PlainSequence {
        sequence<int32> value;
    };

    @nested
    struct PlainArray {
        int32 value[3];
    };

    @nested
    struct PlainMap {
        map<string, string> value;
    };

    @nested
    struct PlainString {
        string value;
    };

    @nested
    struct PlainWideString {
        wstring value;
    };

    @bit_bound(8)
    bitmask PlainBitmask8 {
        FLAG_FOO = 1,
        FLAG_BAR = 3,
        FLAG_BAZ = 7
    };

    @bit_bound(16)
    bitmask PlainBitmask16 {
        B16_FLAG = 15
    };

    @bit_bound(32)
    bitmask PlainBitmask32 {
        B32_FLAG = 31
    };

    @bit_bound(64)
    bitmask PlainBitmask64 {
        B64_FLAG = 63
    };

    @nested
    union PlainUnion switch(octet) {
    case 0:
        int32 my_int;
    case 1:
        float my_float;
    case 2:
        string my_str;
    };

    @nested
    struct ComplexStruct {
        @default({true, 1, 2, 3, 4, 5, 6, 7, 8, 1.5, 1.5, "c", "c"})
        PlainStruct plain_struct;
        PlainSequence plain_seq;
        PlainArray plain_array;
        PlainMap plain_map;
        PlainUnion plain_union;
    };

    @nested
    struct ComplexSequence {
        sequence<ComplexStruct> value;
    };

    @nested
    struct BaseStruct {
        string base_str;
    };

    @nested
    struct DerivedStruct : BaseStruct {
        string derived_str;
    };

    @nested
    struct MultiDerivedStruct : DerivedStruct {
        string multi_derived_str;
    };

    @nested
    struct RecursiveA;

    @nested
    struct RecursiveB {
        uint32 id;
        RecursiveA a;
    };

    @nested
    struct RecursiveA {
        sequence<RecursiveB> b;
    };

    typedef sequence<string> MyStringSeq;

    @nested
    struct UsesAlias {
        MyStringSeq value;
    };

    @nested
    struct SimpleDefault {
        @default(5) int32 value;
    };

    @nested
    struct HasOptional {
        @optional string value;
    };

    @nested
    union OptionalUnion switch(PlainEnum) {
    case PLAIN_FOO:
    case PLAIN_BAR:
        @optional string value;
    case PLAIN_BAZ:
        @optional int32 other;
    };

    @nested
    struct MultiDimArray {
        int32 value[2][3][4];
    };
};

module ext {
    @final
    struct FinalStruct {};

    @mutable
    struct MutableStruct {};

    struct AppendableStruct {};

    @nested
    struct NestedStruct {};

    @autoid(HASH)
    struct HashIdStruct {
        string value;
    };
};

// Regression test for COMPAS-4602 with customer-provided types.
module reference {
    enum ReferenceFrame {
        REFERENCE_FRAME__PANORAMA_HOME,
        REFERENCE_FRAME__PANORAMA_NEW_ROUND,
        REFERENCE_FRAME__PAN_TILT_HOME,
        REFERENCE_FRAME__BODY,
        REFERENCE_FRAME__ABSOLUTE
    };

    typedef octet UUID[16];

    @nested
    struct HeaderStatus {
        UUID sourceResourceId;
    };

    typedef string IpAddress;

    @mutable
    struct Panorama {
        HeaderStatus header;
        uint32 numberOfSegments;
        uint32 transferBitRate;
        double horizontalFov;
        double azOffset;
        ReferenceFrame referenceFrame;
        IpAddress multicastIp[10];
        sequence<uint32, 10> multicastPort;
    };
};

