// Copyright 2024 KONGSBERG
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions are met:
//
// 1. Redistributions of source code must retain the above copyright notice,
//    this list of conditions and the following disclaimer.
//
// 2. Redistributions in binary form must reproduce the above copyright notice,
//    this list of conditions and the following disclaimer in the documentation
//    and/or other materials provided with the distribution.
//
// 3. Neither the name of the copyright holder nor the names of its contributors
//    may be used to endorse or promote products derived from this software
//    without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS “AS IS” AND
// ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
// WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
// DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
// FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
// DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
// SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
// CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
// OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
// OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

#pragma once

module ast {

union Type;

union Item;

union Expr;

union InterfaceMember;

struct Unary;

struct Binary;

struct NamedExpr;

struct EnumDef;

struct BitmaskDef;

struct ConstDef;

struct Field;

@nested
@ext::suppress(language="rust")
struct Position {
    /// Byte offset to the position.
    uint32 offset;

    /// The ID of the file from which this position was derived.
    uint32 file_id;
};

@nested
@ext::suppress(language="rust")
struct Span {
    /// The start position of the span.
    Position start;

    /// The end position of the span.
    Position end;
};

@nested
struct Ident {
    /// The actual identifier.
    string name;

    /// Span of the symbol.
    Span span;
};

@nested
struct Path {
    @optional Span leading_colons;
    sequence<Ident> segments;
};

enum LitKind {
    LIT_BOOL,
    LIT_INT,
    LIT_FLOAT,
    LIT_CHAR,
    LIT_STRING
};

@nested
union LiteralValue switch(LitKind) {
case LIT_BOOL:
     boolean bool;
case LIT_INT:
     uint64 int;
case LIT_FLOAT:
     double _float;
case LIT_CHAR:
     char _char;
case LIT_STRING:
     string _string;
};

@nested
struct Literal {
    Span span;
    LiteralValue value;
};

enum OpKind {
    /// `+`
    OP_ADD,

    /// `-`
    OP_SUB,

    /// `*`
    OP_MULTIPLY,

    /// `/`
    OP_DIVIDE,

    /// `%`
    OP_MODULO,

    /// `<<`
    OP_LSHIFT,

    /// `>>`
    OP_RSHIFT,

    /// `|`
    OP_OR,

    /// `^`
    OP_XOR,

    /// `&`
    OP_AND,

    /// `~`
    OP_NOT
};

@nested
struct Op {
    /// Span of the token.
    Span span;

    /// The operation kind.
    OpKind kind;
};

enum ExprKind {
    /// A single literal like `1` or `"foo"`
    EXPR_LITERAL,

    /// A possibly scoped identifier like `foo` or `::foo::bar`
    EXPR_PATH,

    /// `-a` or `a`
    EXPR_UNARY,

    /// `a + b`
    EXPR_BINARY,

    /// Initializer list for complex types, e.g. `{1, 2, {3}}`
    EXPR_INIT_LIST
};

@nested
struct InitList {
    sequence<NamedExpr> values;
};

@nested
union Expr switch(ExprKind) {
case EXPR_LITERAL:
    Literal literal;
case EXPR_PATH:
    Path path;
case EXPR_UNARY:
    @external Unary unary;
case EXPR_BINARY:
    @external Binary binary;
case EXPR_INIT_LIST:
    InitList init_list;
};

@nested
struct NamedExpr {
    @optional Ident ident;
    Expr value;
};

@nested
struct Unary {
    Op op;
    Expr expr;
};

@nested
struct Binary {
    Expr lhs;
    Op op;
    Expr rhs;
};

@nested
struct AnyType {
    Span span;
};

@nested
struct SequenceType {
    @external Type ty;
    @optional Expr bound;
    Span span;
};

@nested
struct StringType {
    boolean wide;
    @optional Expr bound;
    Span span;
};

@nested
struct MapType {
    @external Type key;
    @external Type value;
    @optional Expr bound;
    Span span;
};

@nested
struct Fixed {
    Expr total;
    Expr fractional;
};

@nested
struct FixedType {
    Span span;
    @optional Fixed bounds;
};

enum TypeKind {
    TYPE_ANY,
    TYPE_SEQUENCE,
    TYPE_STRING,
    TYPE_MAP,
    TYPE_FIXED,
    TYPE_PATH
};

@nested
union Type switch(TypeKind) {
case TYPE_ANY:
    /// The `any` type.
    AnyType _any;

case TYPE_SEQUENCE:
    /// Sequence of another type, e.g. `sequence<string>`.
    SequenceType _sequence;

case TYPE_STRING:
    /// A possibly bounded string.
    StringType _string;

case TYPE_MAP:
    /// (key, value) pair of types, e.g. `map<string, string>`.
    MapType _map;

case TYPE_FIXED:
    /// Fixed-point type, e.g. `fixed` or `fixed<4, 2>`.
    FixedType _fixed;

case TYPE_PATH:
    /// A possibly qualified identifier of a type, e.g. `foo::Bar`.
    Path path;
};

enum DeclaratorKind {
    /// A single, non-qualified identifier.
    DECLARATOR_SIMPLE,

    /// An array declarator, e.g. `value[3][4][5]`.
    DECLARATOR_ARRAY
};

@nested
struct ArrayDeclarator {
    Ident ident;
    sequence<Expr> bounds;
};

@nested
union Declarator switch(DeclaratorKind) {
case DECLARATOR_SIMPLE:
    Ident simple;
case DECLARATOR_ARRAY:
    ArrayDeclarator array;
};

/// A parameter inside an applied annotation, e.g. `value=true` in
/// `@optional(value=true)`.
@nested
struct AnnotationArg {
    /// Name of the parameter if one was specified.
    /// May be omitted for annotations with only a single, non-default member,
    /// but this is not enforced by the parser.
    @optional Ident ident;

    /// Span of the entire parameter.
    Span span;

    /// The specified value of the parameter.
    Expr value;
};


@nested
struct AnnotationAppl {
    Path ident;
    Span span;
    sequence<AnnotationArg> args;
};

@nested
@ext::suppress(language="rust")
struct IDecl {
    /// Span of the entire item, from start to end. For example, given the
    /// following IDL:
    ///
    /// ```idl
    /// module foo { ... };
    /// ````
    ///
    /// The span of the above module will start at 'm' and end at '}'.
    Span span;

    /// Annotations that were applied to this item.
    sequence<AnnotationAppl> annotations;
};

@nested
@ext::suppress(language="rust")
struct IDef : IDecl {
    /// Name of the item.
    Ident ident;
};

enum AnnotationFieldKind {
    FIELD_DEFINITION,
    FIELD_MEMBER
};

@nested
struct AnnotationMember : IDecl {
    Declarator decl;
    Type ty;
    @optional Expr _default;
};

@nested
union AnnotationField switch(AnnotationFieldKind) {
case FIELD_DEFINITION:
    @external Item item;
case FIELD_MEMBER:
    @external AnnotationMember member;
};

@nested
struct AnnotationDef : IDef {
    sequence<AnnotationField> params;
};

@nested
struct ModuleDef : IDef {
    sequence<Item> definitions;
};

@nested
struct Field : IDecl {
    sequence<Declarator> names;
    Type ty;
};

@nested
struct StructDef : IDef {
    sequence<Field> members;
    @optional Path parent;
};

@nested
struct Discriminator {
    sequence<AnnotationAppl> annotations;
    Type ty;
};

@nested
struct Empty {};

enum LabelKind {
    LABEL_CASE,
    LABEL_DEFAULT
};

@nested
union Label switch(LabelKind) {
case LABEL_CASE:
    Expr _case;
case LABEL_DEFAULT:
    Empty _default;
};

enum UnionElementKind {
    ELEMENT_MEMBER,
    ELEMENT_NULL
};

@nested
struct UnionMember {
    @external Type ty;
    Declarator decl;
};

@nested
struct UnionNull {
    Span span;
};

@nested
union UnionElement switch(UnionElementKind) {
case ELEMENT_MEMBER:
    UnionMember member;
case ELEMENT_NULL:
    UnionNull _null;
};

@nested
struct UnionField : IDecl {
    /// Case labels that map to this variant.
    sequence<Label> labels;

    UnionElement field;
};

@nested
struct UnionDef : IDef {
    /// The discriminator component of the union.
    Discriminator disc;

    /// All variants of the union. The case labels that map to each variant can
    /// be found in `UnionField`.
    sequence<UnionField> fields;
};

@nested
struct ConstDef : IDecl {
    Declarator decl;
    Type ty;
    Expr value;
};

@nested
struct Enumerator {
    Ident ident;
    sequence<AnnotationAppl> annotations;

    /// An explicit value, e.g. `enum Foo { VALUE = 1 };`
    /// The `@value` annotation will *not* populate this field.
    @optional Expr value;
};

@nested
struct EnumDef : IDef {
    sequence<Enumerator> fields;
};

@nested
struct ExceptDef : IDef {
    sequence<Field> members;
};

@nested
struct AliasDef : IDecl {
    /// List of all declarators. Always contains at least one declarator.
    sequence<Declarator> decl;

    /// The underlying type of the typedef.
    Type ty;
};

@nested
struct Bit : IDef {
    @optional Expr value;
};

@nested
struct BitmaskDef : IDef {
    sequence<Bit> bits;
};

@nested
struct Bitfield : IDef {
    Expr size;
    @optional Type ty;
};

@nested
struct BitsetDef : IDef {
    @optional Path parent;
    sequence<Bitfield> fields;
};

@nested
struct Attribute {
    /// Name of the attribute.
    sequence<Declarator> decl;

    ///
    sequence<Path> _setraises;

    ///
    sequence<Path> _getraises;

    /// The type of the attribute.
    Type ty;

    /// Indicates whether this attribute was marked as `readonly`, and if
    /// so, the span of the keyword.
    @optional Span _readonly;
};

enum ParamKind {
    /// Explicitly marked as `in`
    PARAM_IN,

    /// Explicitly marked as `out`
    PARAM_OUT,

    /// Explicitly marked as `inout`
    PARAM_INOUT
};

@nested
struct Param {
    /// Name of the parameter.
    Declarator decl;

    /// Type of the parameter.
    Type ty;

    /// Specifies whether this is an `in`, `out`, or `inout` parameter.
    @optional ParamKind kind;
};

@nested
struct Prototype {
    /// Name of the prototype.
    Ident ident;

    /// Return type.
    Type ret;

    sequence<Param> params;
    sequence<Path> _raises;

    /// Indicates whether this function was prefixed with the `oneway` keyword.
    /// Does not account for the `@oneway` annotation.
    @optional Span _oneway;
};

@nested
struct InterfaceDef : IDef {
    sequence<InterfaceMember> members;
    sequence<Path> inherits;
    @optional Span _local;
};

@nested
struct ValueMember {
    Ident ident;
    Type ty;
    @optional Span _public;
};

@nested
struct ValuetypeDef : IDef {
    sequence<ValueMember> members;
    sequence<Prototype> prototypes;
    sequence<Item> definitions;
    @optional Path inherits;
    @optional Path _supports;
};

enum DeclKind {
    DECL_STRUCT,
    DECL_UNION,
    DECL_NATIVE,
    DECL_INTERFACE,
    DECL_VALUETYPE
};

@nested
struct Decl : IDef {
    DeclKind kind;
};

enum ItemKind {
    /// A definition of an annotation
    ITEM_ANNOTATION,

    /// Module declaration
    ITEM_MODULE,

    /// Struct definition
    ITEM_STRUCT,

    /// Union definition
    ITEM_UNION,

    /// Enum definition
    ITEM_ENUM,

    /// Exception definition
    ITEM_EXCEPTION,

    /// Bitmask definition
    ITEM_BITMASK,

    /// Bitset definition
    ITEM_BITSET,

    /// Declaration of a `const`
    ITEM_CONST,

    /// Typedef definition
    ITEM_TYPEDEF,

    /// Interface definition
    ITEM_INTERFACE,

    /// Valuetype definition
    ITEM_VALUETYPE,

    /// A forward declaration
    ITEM_DECL
};

@nested
union Item switch(ItemKind) {
case ITEM_ANNOTATION:
    /// A definition of an annotation
    AnnotationDef annotation_value;

case ITEM_MODULE:
    /// Module declaration
    ModuleDef module_value;

case ITEM_STRUCT:
    /// Struct definition
    StructDef struct_value;

case ITEM_UNION:
    /// Union definition
    UnionDef union_value;

case ITEM_ENUM:
    /// Enum definition
    EnumDef enum_value;

case ITEM_EXCEPTION:
    /// Exception definition
    ExceptDef exception_value;

case ITEM_BITMASK:
    /// Bitmask definition
    BitmaskDef bitmask_value;

case ITEM_BITSET:
    /// Bitset definition
    BitsetDef bitset_value;

case ITEM_CONST:
    /// Declaration of a `const`
    ConstDef const_value;

case ITEM_TYPEDEF:
    /// Typedef definition
    AliasDef alias_value;

case ITEM_INTERFACE:
    /// Interface definition
    InterfaceDef interface_value;

case ITEM_VALUETYPE:
    /// Valuetype definition
    ValuetypeDef valuetype_value;

case ITEM_DECL:
    /// A forward declaration
    Decl decl_value;
};

enum InterfaceMemberKind {
    /// An interface attribute.
    INTERFACE_ATTRIBUTE,

    /// Function definition.
    INTERFACE_PROTOTYPE,

    /// Type definition nested inside the interface.
    INTERFACE_ITEM
};

@nested
union InterfaceMember switch(InterfaceMemberKind) {
case INTERFACE_ATTRIBUTE:
    /// An interface attribute.
    Attribute attr;

case INTERFACE_PROTOTYPE:
    /// Function definition.
    Prototype proto;

case INTERFACE_ITEM:
    /// Type definition nested inside the interface.
    Item item;
};

}; // module ast
