# Copyright 2024 KONGSBERG
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice,
#    this list of conditions and the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above copyright notice,
#    this list of conditions and the following disclaimer in the documentation
#    and/or other materials provided with the distribution.
#
# 3. Neither the name of the copyright holder nor the names of its contributors
#    may be used to endorse or promote products derived from this software
#    without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
# OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == "main"
    - if: $CI_PIPELINE_SOURCE == "schedule"

stages:
  - .pre
  - lint
  - test

variables:
  CI_IMAGE: $CI_REGISTRY_IMAGE/x86_64-unknown-linux-musl:latest

build:ci-image:
  stage: .pre
  image: docker:27
  services:
    - docker:27-dind
  variables:
    DOCKER_TLS_CERTDIR: "/certs"
  rules:
    - if: $CI_PIPELINE_SOURCE == "schedule"
      when: never
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      changes: [ci/x86_64-unknown-linux-musl/Dockerfile]
    - if: $CI_COMMIT_BRANCH == "main"
      changes: [ci/x86_64-unknown-linux-musl/Dockerfile]
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin "$CI_REGISTRY"
  script:
    - docker build -t "$CI_IMAGE" ci/x86_64-unknown-linux-musl/
    - docker push "$CI_IMAGE"

default:
  image: $CI_IMAGE

lint:rustfmt:
  stage: lint
  needs:
    - job: build:ci-image
      optional: true
  script:
    - cargo +nightly fmt -- --check

lint:clippy:
  stage: lint
  needs:
    - job: build:ci-image
      optional: true
  tags: [saas-linux-medium-amd64]
  script:
    - cargo clippy --workspace --all-targets -- -Dwarnings

lint:license:
  stage: lint
  needs:
    - job: build:ci-image
      optional: true
  script:
    - cargo xtask deny

lint:ipr:
  stage: lint
  needs:
    - job: build:ci-image
      optional: true
  script:
    - cargo xtask ipr

test:stable:
  stage: test
  needs:
    - job: build:ci-image
      optional: true
  tags: [saas-linux-medium-amd64]
  script:
    - cargo nextest run --workspace --all-targets --profile ci --config-file ci/nextest.toml
  artifacts:
    when: always
    reports:
      junit: target/nextest/ci/junit.xml
