# Copyright 2024 KONGSBERG
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice,
#    this list of conditions and the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above copyright notice,
#    this list of conditions and the following disclaimer in the documentation
#    and/or other materials provided with the distribution.
#
# 3. Neither the name of the copyright holder nor the names of its contributors
#    may be used to endorse or promote products derived from this software
#    without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
# OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == "main"
    - if: $CI_PIPELINE_SOURCE == "schedule"

default:
  image: "alpine:3.22"
  before_script:
    - apk add --no-cache rustup cmake mold git gcc g++ samurai musl-dev clang-extra-tools cargo-deny cargo-nextest sed
    - rustup-init --profile minimal --default-toolchain 1.88.0 -y
    - source $HOME/.cargo/env

stages:
  - lint
  - test

lint:rustfmt:
  stage: lint
  needs: []
  script:
    - rustup toolchain install nightly -c rustfmt
    - cargo +nightly fmt -- --check

lint:clippy:
  stage: lint
  needs: []
  tags:
    - saas-linux-medium-amd64
  script:
    - rustup component add clippy
    - cargo clippy --workspace --all-targets -- -Dwarnings

lint:license:
  stage: lint
  needs: []
  script:
    - cargo xtask deny

lint:ipr:
  stage: lint
  needs: []
  script:
    - cargo xtask ipr

test:stable:
  stage: test
  needs: []
  tags:
    - saas-linux-medium-amd64
  script:
    - cargo nextest run --workspace --all-targets
