// Copyright 2024 KONGSBERG
//
// Redistribution and use in source and binary forms, with or without
// modification, are permitted provided that the following conditions are met:
//
// 1. Redistributions of source code must retain the above copyright notice,
//    this list of conditions and the following disclaimer.
//
// 2. Redistributions in binary form must reproduce the above copyright notice,
//    this list of conditions and the following disclaimer in the documentation
//    and/or other materials provided with the distribution.
//
// 3. Neither the name of the copyright holder nor the names of its contributors
//    may be used to endorse or promote products derived from this software
//    without specific prior written permission.
//
// THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS “AS IS” AND
// ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
// WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
// DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
// FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
// DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
// SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
// CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
// OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
// OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

struct Color {
    string name;
    octet red;
    int32 green;
    double blue;
};

// C-style designated initializer
// TODO: name is ignored, order matters
// const Color MY_COLOR = {
//     .red = 1 + 2,
//     .green = -128,
//     .blue = 123.456,
//     .name = "blurple"
// };
const Color MY_COLOR = {
    .name = "blurple",
    .red = 1 + 2,
    .green = -128,
    .blue = 123.456
};

// InterCOM variation
const Color MY_COLOR2 = {
    name = "blurple",
    red = 1 + 2,
    green = -128,
    blue = 123.456
};

// Unnamed
const Color MY_COLOR3 = {"foo", 1, 2, 3.0};

// Empty initializer -- all members should use their respective default values.
// const Color MY_COLOR4 = {};

struct HasOptional {
    @optional string value;
};

const HasOptional HAS_VALUE = { "foo" };
const HasOptional NO_VALUE = { null };
